import type { Metadata } from 'next';
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/appSidebar';
import { Separator } from '@radix-ui/react-separator';

import Account from '@/components/account';
import { auth } from '@/lib/auth';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function layout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  if (!session) redirect('/signin');

  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
          <SidebarTrigger className="-ml-1" />
          <Separator orientation="vertical" className="mr-2 h-4" />
          <Account session={session} />
        </header>
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
